### PR TITLE
some improvement in ce_dd_prg

### PR DESCRIPTION
**Pull request by miniupnp**
I tried to improve readability, maintainability.
And it doesn't hurt if size or speed is improved too ;)

### CODE REVIEW

**Comment by atarijookie** [comment]
Holy cow, so many things changed - I suggest to run the filesystem test
with this new version on st, ste, tt and falcon before releasing...
otherwise - nice :)

**Comment by miniupnp** [comment]
indeed it needs to be fully tested before merging. I'm testing on STE and will update with the results.
(I have already, but I'm not sure I tested the latest version ;)

**Comment by miniupnp** [comment]
everything OK on my TOS 1.06 STE.

**Comment by atarijookie** [comment]
Thank you for your wonderful work. :+1:

**Pull request merged**
