### PR TITLE
Show USB drive label on Atari desktop

### PR DESCRIPTION
**Pull request by miniupnp**
instead of showing only "USB DRIVE", now the real "MSDOS" volume label is shown, as on Windows ;)
I tested with FAT/FAT32 formated sticks with the Yocto.
Have to be tested on raspbian

### CODE REVIEW

**Comment by miniupnp** [comment]
it looks like that :
screenshot-000

**Comment by atarijookie** [comment]
Wow, thank you for the nice feature! :)

**Comment by miniupnp** [comment]
I'm adding this :
screenshot-002

**Comment by miniupnp** [comment]
see e74d88f2cc8ed50e54c6e336b15875f1f7cb9bbb and bc491a8bdcdf158d22007f02a7f519d87c2fad06

**Comment by miniupnp** [comment]
can someone test with Raspbian ?

**Comment by atarijookie** [comment]
I will try if it I'll get to it....

**Comment by miniupnp** [comment]
it should work as long as /dev/disk/by-label/ contains the labels

**Comment by atarijookie** [comment]
I saw the new name on destop - cool :) Although 'VOYAGER 2GB' resulted to 'VOYAGER\x202' - space character got translated to 0x20.

```
ce_raspbian # ls -l /dev/disk/by-label/
total 0
lrwxrwxrwx 1 root root 15 Nov 21 10:17 boot -> ../../mmcblk0p1
lrwxrwxrwx 1 root root 10 Nov 25 04:17 VOYAGER\x202GB -> ../../sda1
```

I didn't see the changed name in mounter.prg though - are those two commits in my master, or are they located somewhere else? I've looked at my translateddisk_genera.cpp:555 and it doesn't have that change yet...

**Comment by mikrosk** [comment]
Actually, I wanted to ask the same: how can I know which repository/branch is your commit from? Because if I click on the two commits above, I see this:
image
Only going to your github profile, knowing that it's `ce-atari` and looking into `usb_labels` branch has revealed what I have to fetch from. I'd assume that github shows me *your* repository and the exact branch.

So the short answer is no, it's not in your master.

**Comment by mikrosk** [comment]
Cherry-picked your last two commits and tried on my setup, both of my USB sticks keep unrecognised -- but yeah, it's because /dev/disk/by-label/ shows nothing.

**Comment by atarijookie** [comment]
> So the short answer is no, it's not in your master.

Damn, so it's in the usb_labels branch, which is not retrieved when I do git pull...

> Cherry-picked your last two commits and tried on my setup, both of my USB sticks keep unrecognised -- but yeah, it's because /dev/disk/by-label/ shows nothing.

And how does it look then? Empty strings, or shows 'USB drive' as before?

**Comment by mikrosk** [comment]
Yep, USB Drive as before.

**Comment by miniupnp** [comment]
I think you merged before I pushed this commit.
just merge again my usb_label branch :)

I will add code to translate non standard characters

**Comment by mikrosk** [comment]
> I think you merged before I pushed this commit.
> just merge again my usb_label branch :)

That's the point, we shouldn't do that. The proper way is to update your pull request.

**Comment by miniupnp** [comment]
I updated the merge request

**Comment by miniupnp** [comment]
@mikrosk what do you mean ? if he merged before I added the new commits to the pull request, he has to merge again... 
I did add the new commits to the branch, and will add more to fix the x20 issue ;)

**Comment by miniupnp** [comment]
BTW I personnally dont like what github does when merging with the web.
I prefer do the merge myself with git, because fast forward merge are allowed.

**Comment by mikrosk** [comment]
@miniupnp: I did see your commits (part of your `usb_label` branch) before Jookie's post. I wanted to try it personally so I spent a fair amount of time finding them. :D Then I found them in the branch.

So if you're updating your code, always update merge request, too else others depend on their knowledge of your branch names etc.

I'm not very excited about github's UI either, as mentioned, I'd at least prefer to see the name of your branch, where the commit comes from, not only parent commit IDs...

**Comment by miniupnp** [comment]
I updated my usb_labels branch with fix for the \x20 issue
just checkout my branch to test it

**Comment by miniupnp** [comment]
Adding commits to a branch does update the Pull request automatically

but here it looks like the PR is closed and so it won't be updated.

**Comment by atarijookie** [comment]
Merged and pushed to master, thank you for your contribution :) :+1:

**Comment by mikrosk** [comment]
> but here it looks like the PR is closed and so it won't be updated.

Perhaps that's the culprit. Good to know. And thank you for the nice feature. :)

**Pull request merged**
