### PR TITLE
Revert "make depend"

### PR DESCRIPTION
**Pull request by atarijookie**
Reverts atarijookie/ce-atari#35

### CODE REVIEW

**Comment by atarijookie** [comment]
@miniupnp  - this is weird, after those changes I can't safely do 'make clean' - it starts building stuff, then it does clean at the end. And when I do 'make', it builds longer than before... Something is broken here...

**Comment by miniupnp** [comment]
it has to build .d files (dependencies).

there is indeed an issue. make clean first build dependencies before cleaning them :)
its because of the -include directive.

if forgot a ifneq

**Comment by miniupnp** [comment]
you should not commit "revert" patches.
Just git checkout / git push to come back before the merge !

**Comment by miniupnp** [comment]
sorry :
git reset f6b9d0139bb826493dd605a8ea0f53861b32ac6b
git push origin master

**Comment by atarijookie** [comment]
Argh, I'm sorry, I'm still new to this git thing... Should I do that 'git reset + git push' thing now, or it's just how I should do it in the future?

**Comment by miniupnp** [comment]
I'm not using git reset frequently, I have to check whether --hard should be used :)

**Comment by atarijookie** [comment]
It seems that I can't do 'git reset --hard' to older revision and then push it, because it says:

> Updates were rejected because the tip of your current branch is behind its remote counterpart. 

Ow, well, I guess we should leave it like that...

**Comment by miniupnp** [comment]
well the issue is that now you can't merge my fix anymore...

**Comment by miniupnp** [comment]
the revert "lost" git :=)

**Comment by atarijookie** [comment]
> well the issue is that now you can't merge my fix anymore...

What if you would create a diff, which I would apply and push?

**Comment by miniupnp** [comment]
ok so just : 
First make sure all your changes are commited. if your local repo has "unpushed" commits, just create a new local branch for it, using `git checkout -b new_branch`
Then :

```
git checkout master
git reset f7fb5bfddfd0e04f7196140e0f03148aeb78fc03
git push --force origin master
```

1) insure your local branch is master
2) reset local master to f7fb5bfddfd0e04f7196140e0f03148aeb78fc03 which is the commit it was before you merged my branch.
3) push to github (I'm assuming origin is https://github.com/atarijookie/ce-atari change to whatever is suitable)

Then we'll be able to work as usual :)

**Comment by miniupnp** [comment]
I've also assumed you already `git fetch --all`  so your "remotes" are in sync :)

I'm not sure if I already told you, but using `git log --graph --decorate --all` (between each critic command) is a good idea to know where you are :)

**Comment by atarijookie** [comment]
OK, I've done that. Is it OK now? :)

**Comment by miniupnp** [comment]
looks pretty good !!!
we're back. You just learnt to "unmerge"  :)

**Pull request merged**
