### PR TITLE
Less polling

### PR DESCRIPTION
**Pull request by miniupnp**
- use pthread_cond in Downloader and Mounter 
- far less polling in peridodic thread (but still a bit)

there is still to do : 
 - timersync thread (to be removed and moved to periodoic thread/download thread) 
 - more improvement in periodic thread

the ccorethread is more difficult, I'm afraid the bcm2835 lib is not able to deliver interrupts without polling

### CODE REVIEW

**Comment by atarijookie** [comment]
Holy moly, so many changes :) Everything seemed to work fine after these changes, right? 
I'm not able to test it all, so I'll rely on your testing. If you're sure it works, I'm fine with merging...

Or maybe @mikrosk could add his opinion?

**Comment by miniupnp** [comment]
It is tested everything looks good:)
I opened the PR so every one can have a look and tell what they think of it

**Comment by miniupnp** [comment]
and one thread less..

**Comment by mikrosk** [comment]
I'd say @miniupnp is our expert on sockets and descriptors, I know how it works but I think I hadn't ever implemented one piece of code with select() in my life (joy of highlevel frameworks and languages...). So if it works, I'm fine with that. :)

**Comment by miniupnp** [comment]
@mikrosk if you don't use select(), then use libevent2 or any other library enabling asynchronous(non blocking) code. Qt is great for that

**Comment by miniupnp** [comment]
If anyone need to test before I merge, just tell me !

**Comment by atarijookie** [comment]
Seems that nobody wants to test it and we trust you, Thomas, so you can merge it :)

**Pull request merged**
