### PR TITLE
-added CE ACSI command ST_LOG_HTTP - simply feed given buffer as URL to cur…

### PR DESCRIPTION
**Pull request by tin-nl**
…l to e.g. log events from ST to a web server
-better logging of IKBD ST-Commands

### CODE REVIEW

**Comment by mikrosk** [comment]
As a person who spent considerable time with debugging IKBD, may I ask:

- what problem are you trying to solve?
- how is this easier than watching the RPi console?

**Comment by tin-nl** [comment]
This contains two unrelated things:
1. ST_LOG_HTTP
2. more debug output for ST command IKBD commands

The formatting of the request might not help in not getting those confused (dang you, github!). Should been two commits, but I made that one a while ago and wanted the pull request out of the door before I forget to do it.

I'm using ST_LOG_HTTP extensively for automated search tools and statistics - e.g. for things like "powercycle the ST until wakestate x is reached" or "did this this ST boot a sub-wakestate that shows Spectrum 512 pixels or bands". This helps enormously to easily trigger the different systems involved.

**Comment by mikrosk** [comment]
Man, that's totally awesome! :)

**Comment by atarijookie** [comment]
I see what you did there and it looks good! :) Anyone else wants to say something before merge?

**Comment by miniupnp** [comment]
it looks cool

**Pull request merged**
