### PR TITLE
use travis-ci.org

### PR DESCRIPTION
**Pull request by miniupnp**
It at least checks everything compiles !

If we get a binary package for atari cross compiler somewhere (I think vincent riviere has an ubuntu repository... to be tested :) we could add compilation of atari programs

@atarijookie go to https://travis-ci.org and enable for ce-atari repository BEFORE this PR is merged

### CODE REVIEW

**Comment by mikrosk** [comment]
I guess you'll be happy to hear that I'm working on just that -- set of .deb packages for trusty with m68k-atari-mint-{gcc, binutils, mintlib, pml}. (Vincent officially supports only latest ubuntus and while you can use his old builds for trusty, I'd recommend to use the latest patches build against trusty -- that's what I'm working on right now).

**Comment by miniupnp** [comment]
@mikrosk we'll need libgem as well :)

**Comment by mikrosk** [comment]
Good news, you'll get that too! :) (it's needed for freemint builds anyway)

**Comment by miniupnp** [comment]
@atarijookie tell me when travis-ci is enabled for you (It will ask to make a commit, I will do :)

**Comment by miniupnp** [comment]
@mikrosk we are missing RPi cross compilers ;)

**Comment by mikrosk** [comment]
@miniupnp actually, I've studied the problem, it's dead-easy. You just want to make sure that the right versions of glibc & friends are installed + the support libraries/headers for BCM hardware. Few days and you'll get it! ;)

**Comment by atarijookie** [comment]
OK, I've enabled the travis CI thing, I've commited the .travis.yml, so it might need some fixing, but at least it's enabled there...

**Comment by miniupnp** [comment]
you shouldn't have commited the .travis.yml, because I have created one :)
anyway, I'm going to merge.

**Comment by miniupnp** [comment]
now all PR and pushes build will be tested

**Comment by miniupnp** [comment]
@mikrosk : is `sudo apt-get install build-essential g++-arm-linux-gnueabihf` enough ? :)

**Comment by miniupnp** [comment]
@atarijookie sorry, I dropped your commit. you may need to `git rebase -i origin/master ` to sync. don't hesitate to contact me (by email ?) if you need help

**Comment by atarijookie** [comment]
@miniupnp Err, so I did the rebase, some commands here and there, some push, commit, push :) Can you check now if I didn't screw up too much? Now I can git pull without a problem.

**Comment by miniupnp** [comment]
@atarijookie looks like you now have 2 pointless commits :)
to remove them :
```
git checkout master
git reset --hard b1ab10ae5359230f6bdc52a980f0aceb574f30b4
git push --force origin master
```

`git log --graph --all --decorate ` just before the push if you want to check everything looks alright ÷)

**Comment by miniupnp** [comment]
it is also possible to rebase -i and squash the 2 commits together

**Comment by mikrosk** [comment]
@miniupnp: from compiler point of view it is enough however you must be careful about library versions. However for fast testing (i.e. testing the build) it's enough.

**Comment by ggnkua** [comment]
BTW, http://brownbot.hopto.org/ is running on a rpi2...

**Comment by miniupnp** [comment]
@mikrosk it looks promising, just need to cross-compile libbcm2835

**Comment by miniupnp** [comment]
libbcm2835 ok, curl to be fixed...

**Pull request merged**
