### PR TITLE
use dependencies for ce_main_app

### PR DESCRIPTION
**Pull request by miniupnp**
was #35 :)

### CODE REVIEW

**Comment by miniupnp** [comment]
0a43ddb2f797552af84416a1edd2cc2f082426f4 fixes issues with "make clean"

**Comment by atarijookie** [comment]
Silly / unimportant question, but wouldn't it be nicer if the clean and depclean were the same on how they delete *.o and *.d files?

Now it is:

```
find . -name "*.o" -exec $(RM) {} \; 
$(RM) $(DEPS) 
```

Could be:

```
find . -name "*.o" -exec $(RM) {} \; 
find . -name "*.d" -exec $(RM) {} \; 
```

...or could be:

```
$(RM) $(OBJS) 
$(RM) $(DEPS) 
```

The find version produces shorted stdout output on 'make clean' :) Otherwise it seems OK now.

**Comment by miniupnp** [comment]
I would go for $(RM) $(OBJS) 
but I think you made the "find" version, so I guess you prefer it :)

**Comment by atarijookie** [comment]
Nope, it was improvement by tIn if I remember correctly, but I like the 'find' version because of the shorter console output :)

**Comment by miniupnp** [comment]
@ could be used for shorter console output

**Comment by atarijookie** [comment]
'@' used, branch / pull request merged. Thank you for improvement and help with git stuff :)

**Comment by miniupnp** [comment]
http://stackoverflow.com/questions/9314322/controlling-verbosity-of-make

**Pull request merged**
