### PR TITLE
Blitter enable

### PR DESCRIPTION
**Pull request by miniupnp**
enable blitter in DESKTOP.INF.
Have to be tested on a machine without blitter (I have none :)

### CODE REVIEW

**Comment by atarijookie** [comment]
Blitter Enable thing enables blitter on my STFM with TOS 1.02, but it doesn't cause any issues (no ST crash on boot), so I guess it's fine. 

The other thing is, that this pull request (blitter enable) contains all the mounter changes, and also change to the filesystem test... All these things look ok, mounter works fine with windows sharing (will test nfs tomorrow), but I thought  the point of having branches / pull requests is to have new features nicely separated, so they could be pulled independently if needed :) But I guess I could (somehow) pull individual commits for testing if needed...

**Comment by miniupnp** [comment]
yes I made a mistake, I should have restarted from your master branch:)
You can cherry pick https://github.com/atarijookie/ce-atari/pull/24/commits/2414fb4406ec7aec359ed28e1c9829a5002baa20 instead of merging the whole PR :)

**Comment by atarijookie** [comment]
I could cherry pick, if I only knew how ;) Learning git keeps be entertained, instead of doing real stuff :-D

**Comment by miniupnp** [comment]
`git cherry-pick 2414fb4`

**Comment by atarijookie** [comment]
Hey, thanks ;) I didn't think it's a literal git command :+1:

**Comment by tin-nl** [comment]
From my experience: everything after "You just could" in a sentence regarding git exists as a literal git command ;)

**Comment by atarijookie** [comment]
Works with samba, seems to fail with NFS.

This is the log, when trying to mount NFS folder:

```
Mounter::mount - mount failed. (mount dir: /mnt/shared)
Mounter::mount - mount error : Invalid argument
Mounter::mount - type=nfs source='192.168.255.4:/c/icc' options='nolock'
Mounter::mount - mount failed. (mount dir: /mnt/shared)
Mounter::mount - mount error : Invalid argument
Mounter::mount - type=nfs source='192.168.255.4:/c/icc' options='nolock'`
```

However, mount succeeds just fine:
[screenshot from qemu](http://i63.tinypic.com/20u8m5x.png)

Server HaneWin NFS server for Windows (a small server app). 

@miniupnp - can you take a look at that ^^^ ?

**Comment by atarijookie** [comment]
Mounter changes merged before from the other pull request.
Blitter enable feature merged from this pull request.

**Pull request merged**
