### PR TITLE
Screencast improvement

### PR DESCRIPTION
**Pull request by miniupnp**
is now able to take screenshot of maxYMiser or some demo/intros.
Tested on my STE.

There is still a lot to do, for example to support TT and Falcon.

### CODE REVIEW

**Comment by tin-nl** [comment]
So this is screenshot only, not screencast, right? Or did i miss something?

**Comment by atarijookie** [comment]
Wow, thank you :)

**Comment by miniupnp** [comment]
does anyone has a TT or Falcon here ?

**Comment by tin-nl** [comment]
@minupnp: Both - I can check things there if this helps :)
 Would have to port it over to screencast anyway, if I saw correctly (see previous comment). I still have a branch with some screencast changes re Falcon/TT I have to revisit and test (see https://github.com/atarijookie/ce-atari/tree/screencast_res)

**Pull request merged**
