### PR TITLE
Floppy code simplification in ce_main_app

### PR DESCRIPTION
**Pull request by miniupnp**
properly use C++ inheritance to simplify FloppyImageSt/FloppyImageMsa
duplicated code is the easiest way to duplicate bugs !

also use pthread_cond for Floppy encoding thread

### CODE REVIEW

**Comment by miniupnp** [comment]
@atarijookie I tested quickly and it looks like it works : images are loaded into the slots. But the floppy interface is not connected to my ST so I've not checked the proper floppy leads :)

**Comment by atarijookie** [comment]
> properly use C++ inheritance to simplify FloppyImageSt/FloppyImageMsa

Nice ;) It was done with that in mind, but I didn't get to do it properly, big thumbs up! :+1:

**Comment by miniupnp** [comment]
@atarijookie do you want to test before I merge ?

**Comment by atarijookie** [comment]
No, if I'll do the testing, I'll use my free time on that instead of fixing other things, so I'll just trust you on and hope that it's really OK :)

**Pull request closed without merging**
