### PR TITLE
CE Sting

### PR DESCRIPTION
**Pull request by miniupnp**
Build cleanup

and try to fix issue #14 by : 
1) not masking other interrupts
2) only installing VBL hander if absolutly necessary.

I tested with IRC.TOS, everything works fine.
I guess it needs some more testing before merging ;)

### CODE REVIEW

**Comment by miniupnp** [comment]
read sting when I write string :-(

**Comment by atarijookie** [comment]
I will merge it now without testing, because the only major change there is the 'Do not install VBL handler unless it is necessary' and I've used ce_sting without the VBL and it worked fine - it needs VBL mainly for ICMP processing, but it could also speed up some data receiving... 

For the test of crashing / not crashing after not masking all ints I would temporarily enable VBL always, then use some client which uses mouse (that would exclude IRC.TOS) - e.g. Litchi or AFTP, and while you see the VBL runs I would mouse the mouse around - @sqward writes that mouse interaction (which comes in longer ikdb packets) could screw things more easily than just typing on keyboard (the case of IRC.TOS), because the keyboard presses come into ST as single bytes...

**Comment by sqward** [comment]
Just an idea: What application can do in ICMP handlers? Because you call these from interrupt you're not allowed to call TOS/GEM/BIOS form there. Is this limitation also something that original Sting also imposed?

**Comment by atarijookie** [comment]
> Just an idea: What application can do in ICMP handlers?

The PING tool uses ICMP handlers, and I think I've seen one of these FTP clients (Litchi or AFTP) doing ping through ICMP when they were (re)trying to do connection to FTP server.

>  Because you call these from interrupt you're not allowed to call TOS/GEM/BIOS form there.

Drat, drat, and double drat! I hope that all those Sting clients don't use anything from that list. But I guess we can't rely that they won't do it, so what would be a better way to do it? Some other interrupt handler?

> Is this limitation also something that original Sting also imposed?

I have no idea, I've thrown out all the original sources and reused only a little part of it. I could check that later...

**Comment by sqward** [comment]
The alternative would be to queue ICMP callbacks in the interrupt and dispatch them whenever application calls any Sting API funcion (when you gain control). This would ensure that you user application was not in OS code when interrupt was fired because there would be no interrupt involved.

**Comment by atarijookie** [comment]
> The alternative would be to queue ICMP callbacks in the interrupt and dispatch them whenever application calls any Sting API funcion (when you gain control).

This was one of the options in the past, but this resulted in failed pings - e.g. the ping tool from original Sting package does something like this:
1. register icmp handler
2. send N icmp packets
3. wait (sleep) a while
4. unregister icmp handler
5. see how many times the icmp handler was called (once per each received packet)

So in that case you would have all / some of the packets received in 4. (on unregister), and that would result in long ping times (while the real ping time was short). It works fine with original Sting (short ping times shown), so the original Sting doesn't do it this way, but using some interrupts - if not VBL, then some others...

**Comment by sqward** [comment]
How does the ping application sleep? Does it call any system functions for this? Maybe Sting is intercepting TOS/GEM traps?

Do you have access to Sting source code?

**Comment by atarijookie** [comment]
> How does the ping application sleep? Does it call any system functions for this? Maybe Sting is intercepting TOS/GEM traps?

Damn, that's an interesting idea of intercepting TOS/GEM traps for this :+1: 

In sting_src\TOOL\PING\PING.C
on line 126 and 130 it waits using:
evnt_timer (200, 0);

> Do you have access to Sting source code?

It's somewhere on the net, but I can't find it... So here's a link to my dropbox instead:
https://www.dropbox.com/s/vdxz88406rmx6ju/STINGSRC.LZH?dl=0

**Comment by sqward** [comment]
Checked the sources and in developers documentation it says that ICMP handler will be called from interrupt context so this is fine. One thing that I've noticed is that Sting uses timer C interrupt instead of VBL. Have you measured how long does it take to execute your VBL routine?

**Comment by atarijookie** [comment]
> One thing that I've noticed is that Sting uses timer C interrupt instead of VBL.

Then maybe we should do it in a similar (same) way, but I'm not able to do it without c&p from the sources of someone else - I have no experience with these interrupts on ST (I use them on MCUs though).

> Have you measured how long does it take to execute your VBL routine?

No, not yet. Is there a specific time to which the VBL routine must quit to not screw the rest of the system?

**Comment by sqward** [comment]
Well, you need to quit before next VBL routine. Otherwise you'll at least mess up mouse pointer movements. You want to do as little on that interrupt as possible. 

Switching to Timer C is simple. Just use a different interrupt vector (I forgot the address). But I don't think this will fix anything in itself. Getting it work with VBL should probably be a priority.

Was the interrupt masking suggestion effective?

**Comment by atarijookie** [comment]
> You want to do as little on that interrupt as possible.

I'm trying to stick to that - there's only one communication with the device, and then passing the data to  icmp handlers, which I hope don't take extra time also...

> Was the interrupt masking suggestion effective?

I didn't test it yet, but there was a code change (and possible test) by @miniupnp, so maybe he could tell (I wonder if he could reproduce the issue at all before doing the change :) )

**Comment by atarijookie** [comment]
> Was the interrupt masking suggestion effective?

I tried it without that change and with your suggested change (which is already commited by miniupnp), and it seems that it does the job - without it I do get keyboard misbehaving, with it I didn't see it happen yet. Thank you for that! :) Now for the rest of the things to test there...

**Comment by atarijookie** [comment]
> Have you measured how long does it take to execute your VBL routine?

I just made a test with the ping tool from sting package, and I got maximum 2 ticks on the 200 Hz counter, so that could be almost 3 ticks (measurement error) and that also includes calling that icmp handler (and letting it process the data), so that would be up to 15 ms for this execution. 

But... if more icmp packets would arrive at once (e.g. tool would send them faster, or the processing would stop for a while so they would get queued) or the icmp handler would take longer (in other apps?), then it could be just more...

**Pull request merged**
