### PR TITLE
mounter improvements

### PR DESCRIPTION
**Pull request by miniupnp**
use umount() / sync() system calls.
Also mount() system call for cifs and nfs.

note:  it is now possible to merge PR without merge commit to have a cleaner history

### CODE REVIEW

**Comment by atarijookie** [comment]
Mounter works fine with windows sharing (will test nfs tomorrow). Commits from this pull request are the same as in the 'blitter enable' pull request (+ that one has one feature more).

**Comment by miniupnp** [comment]
yes the PR #24 shouldn't had included this one :( sorry

**Comment by atarijookie** [comment]
No problem, I just heard everybody talking how good git / github is on separating things, commits and stuff :-D

**Comment by miniupnp** [comment]
hum trying to install nfs now :)

**Comment by miniupnp** [comment]
with the new fix its working on my linux NFS4.
please test with your nfs3 server :)

**Comment by atarijookie** [comment]
It works now with the NFS shared folder, so I merged it in the master. Thank you for the patches :+1:

**Pull request merged**
